"""fix: rename tittle to title, is_completed to completed

Revision ID: 43f0c5468461
Revises: 8407138540cc
Create Date: 2025-11-20 21:59:01.426956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f0c5468461'
down_revision: Union[str, Sequence[str], None] = '8407138540cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Renomeia colunas existentes
    op.alter_column("tasks", "tittle", new_column_name="title")
    op.alter_column("tasks", "is_completed", new_column_name="completed")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverte o renomeamento das colunas
    op.alter_column("tasks", "title", new_column_name="tittle")
    op.alter_column("tasks", "completed", new_column_name="is_completed")
    
    # ### end Alembic commands ###
